version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:alpine3.16
    restart: always
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres:/docker-entrypoint-initdb.d

  pgadmin4:
    image: dpage/pgadmin4:6.20
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@example.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - "80:80"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: "elasticsearch"
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=root-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_USERNAME=root
      - ELASTIC_PASSWORD=example
      # 默认情况下，您将获得 30 天的试用许可证，其中启用了所有功能（包括安全性），因此，默认情况下，
      # 如果没有用户名 + 密码，则无法访问您的 ES 服务器。 xpack.security.enabled=false禁用安全性
      # 参考 https://discuss.elastic.co/t/401-unauthorized/118943
      - xpack.security.enabled=false
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
