version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:alpine3.16
    restart: always
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres:/docker-entrypoint-initdb.d

  keycloak:
    image: bitnami/keycloak:20.0.3-debian-11-r13
    restart: always
    environment:
      - BASE_URL=http://localhost:8091/
      - APP_NAME=测试系统
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=root
      - KEYCLOAK_DATABASE_PASSWORD=example
      - KEYCLOAK_PROXY=edge
      - KEYCLOAK_HTTP_RELATIVE_PATH=/auth
      - KEYCLOAK_PRODUCTION=true
      # 必须加 --hostname-strict-https=false，否则无法打开 admin 控制台
      # 参考文献 https://www.keycloak.org/server/hostname
      - KEYCLOAK_EXTRA_ARGS=--hostname-strict-https=false -Dkeycloak.import=/tmp/realm.json --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    ports:
      - "8080:8080"
    volumes:
      - ./init-keycloak/realm.json:/tmp/realm.json
      - ./init-keycloak/tp-theme:/opt/bitnami/keycloak/themes/tp-theme
    depends_on:
      - postgres

  zookeeper:
    image: 'bitnami/zookeeper:3.8.0-debian-11-r49'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    restart: always

  # 有关 Kafka Docker 中的配置的关键概念介绍及区分线索
  # 参考文献 https://stackoverflow.com/questions/42998859/kafka-server-configuration-listeners-vs-advertised-listeners
  kafka:
    image: 'bitnami/kafka:3.3.1-debian-11-r5'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  minio:
    image: 'bitnami/minio:2022.10.8-debian-11-r0'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_SERVER_HOST=localhost
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=test-bucket
      - MINIO_NOTIFY_KAFKA_BROKERS_TEST=kafka:9092
      - MINIO_NOTIFY_KAFKA_ENABLE_TEST=on
      - MINIO_NOTIFY_KAFKA_TOPIC_TEST=minio_bucket_notification
    depends_on:
      - kafka
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:6.20
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@example.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - "80:80"
    restart: always

  neo4j:
    image: neo4j:5.9.0
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use_neo4j_config=true
    volumes:
      - ./plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: "elasticsearch"
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=root-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_USERNAME=root
      - ELASTIC_PASSWORD=example
      # 默认情况下，您将获得 30 天的试用许可证，其中启用了所有功能（包括安全性），因此，默认情况下，
      # 如果没有用户名 + 密码，则无法访问您的 ES 服务器。 xpack.security.enabled=false禁用安全性
      # 参考 https://discuss.elastic.co/t/401-unauthorized/118943
      - xpack.security.enabled=false
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
