server:
  port: 8081

spring:
  application:
    name: demo-application
  datasource:
    url: jdbc:postgresql://localhost:5432/hs
    username: root
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            directory.root: ./hs-index
    hibernate:
      ddl-auto: update
  elasticsearch:
    uris: [ "http://localhost:9200" ]
    username: root
    password: example

app:
  reset-with-demo-data: always
